---
name: usbip client
version: 0.1.0
slug: usbipclient
description: USBIP Client Addon for Home Assistant
url: https://github.com/irakhlin/usbip-hassio/tree/main/usbip
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
  - i386
image: irakhlin/usbip-addon-{arch}
ports:
  22/tcp: 22333
ports_description:
  22/tcp: SSH Interface
usb: true
tmpfs: true
kernel_modules: true
devicetree: true
init: false
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RESOURCE
  - SYS_MODULE
  - DAC_READ_SEARCH
options:
  authorized_keys: []
  password: ""
  apks: []
  server:
    tcp_forwarding: false
schema:
  authorized_keys:
    - str
  password: password
  apks:
    - str
  server:
    tcp_forwarding: bool
startup: services