---
name: usbip client
version: 0.3.0
slug: usbipclient
description: USBIP Client Addon for Home Assistant
url: https://github.com/irakhlin/usbip-hassio/tree/main/usbip
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
  - i386
image: irakhlin/usbip-addon-{arch}
ports:
  22/tcp: 22
ports_description:
  22/tcp: SSH Interface
usb: true
tmpfs: true
kernel_modules: true
init: false
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RESOURCE
  - SYS_MODULE
  - DAC_READ_SEARCH
startup: services
options:
  ssh:
    username: hassio
    password: ""
    authorized_keys: []
    sftp: false
    compatibility_mode: false
    allow_agent_forwarding: false
    allow_remote_port_forwarding: false
    allow_tcp_forwarding: false
  zsh: true
  share_sessions: false
  packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  ssh:
    username: str
    password: password
    authorized_keys:
      - str
    sftp: bool
    compatibility_mode: bool
    allow_agent_forwarding: bool
    allow_remote_port_forwarding: bool
    allow_tcp_forwarding: bool
  zsh: bool
  share_sessions: bool
  packages:
    - str
  init_commands:
    - str
