name: "Publish"

on: 
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
        matrix:
          target: ['double-take']
        fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --aarch64 \
            --no-latest \
            -i hassio-addon-${{ matrix.target }}-{arch} \
            --target ${{ matrix.target }} \
            --docker-hub ghcr.io/${{ secrets.DOCKER_USERNAME }}
