name: "Test"

on: [push, pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    strategy:
        matrix:
          target: ['double-take']
        fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --amd64 \
            --aarch64 \
            --no-latest \
            -i hassio-addon-${{ matrix.target }}-{arch} \
            --target ${{ matrix.target }} \
            --docker-hub ${{ secrets.DOCKER_USERNAME }}